---
title: "Collected/Imputed vs FLU 2016"
date: "11/3/2020"
output: 
  html_notebook:
    theme: readable
---

Analysis comparing prev FLU (2016) to what has been collected or imputed.

This analysis uses `J:/Staff/Christy/usim-baseyear/flu/impute_flu_comparison_filled.csv`.

Notes about the data:

* Imputation is based on the following formulas
  - $DU = (max height/15)^2$
  - $FAR = max height/20$
* Columns ending in `_imp` contain both imputed and collected density values

```{r prep data}
library(data.table)
library(tidyverse)
library(patchwork)

df <- fread("J:/Staff/Christy/usim-baseyear/flu/impute_flu_comparison_filled.csv")

# create long format for imputed/current FLU densities
id.cols <- c("Key", "Jurisdicti_new", "Definition_new")  
msr.cols <- str_subset(colnames(df), "_imp")
prev.cols <- str_subset(colnames(df), "_prev")
dfm <- melt(df, id.vars = id.cols, measure.vars = msr.cols, variable.name = "imputed_type", value.name = "imputed_value")

# subset for 2016 columns, remove duplicate rows (b/c orig. format is shapefile)
sub.cols <- c("Key", prev.cols)
dfs <- df[, ..sub.cols]
dfu <- unique(dfs) # remove duplicate rows

# join melted df and add type columns
dfj <- dfm[dfu, on = "Key"]
dfj[, `:=`(dens_type = str_extract(imputed_type, "^Max\\w{2,3}(?=_)"),
             use_type = str_extract(imputed_type, "(?<=_)\\w+(?=_)"))]
# add res type to criteria
dfj[!is.na(Max_FAR_prev) & !is.na(imputed_value) & dens_type == "MaxFAR", max_far_diff := Max_FAR_prev - imputed_value]
dfj[!is.na(Max_DU_Ac_prev) & !is.na(imputed_value) & dens_type == "MaxDU", max_du_diff := Max_DU_Ac_prev - imputed_value]

```

```{r ggplot functions}
scatterplot <- function(df, xvar, yvar, colorvar) {
    ggplot(df) +
    geom_point(aes_string(x = xvar, y = yvar, color = colorvar),
             alpha = .7) +
    geom_abline()
}

dotplot <- function(df, xvar, facetvar) {
  ggplot(df) +
    geom_dotplot(aes_string(xvar), dotsize = .6) +
    scale_y_continuous(NULL, breaks = NULL) +
    facet_grid(. ~ .data[[facetvar]])
}

log_scale <- list(scale_y_log10(), scale_x_log10())

```

```{r, fig.height=5, fig.width=10}
du <- scatterplot(dfj[dens_type == "MaxDU", ], "Max_DU_Ac_prev", "imputed_value", "use_type") +
  labs(title = "Default scale")
du_log <- du + log_scale + labs(title = "Log scale")
du + du_log & labs(y = "Collected & Imputed Value")
```



```{r}
far <- scatterplot(dfj[dens_type == "MaxFAR", ], "Max_FAR_prev", "imputed_value", "use_type")
far + labs(y = "Collected & Imputed Value")
```
```{r, fig.height=10, fig.width=10}
far_diff_dotplot <- dotplot(dfj[dens_type == "MaxFAR"], "max_far_diff", "use_type")
du_diff_dotplot <- dotplot(dfj[dens_type == "MaxDU"], "max_du_diff", "use_type")

far_diff_dotplot + du_diff_dotplot + plot_layout(ncol = 1) & labs(title = "Density Differences by Use Type")
```

